#
# pattern: Can either be the exact "app_name" (app_id/class) of the window or a regex string in the format of `"/{regex}/"` which will match the window "title".
# icon: Your beatifull icon
#
# verbose format:
#
#       '{pattern}' = { type = 'generic' | 'exact', value = '{icon}' }
#
#
# If it couldn't match something it will print:
#
# WARN [sworkstyle:config] No match for '{app_name}' with title '{title}'
#
# You can use {title} to do a generic matching
# You can use {app_name} to do an exact match
fallback = 'ï‹'

[matching]
'discord' = 'ï’'
'balena-etcher' = 'ï‹›'
'Steam' = 'ï†¶'
'vlc' = 'ï€½'
'Postman' = 'ï '
'Bitwarden' = 'ï‚„'
'Google-chrome' = 'ï‰¨'
'/Chrome/' = 'ï‰¨'
'Chromium' = 'ï‰¨'
'Slack' = 'ï†˜'
'Code' = 'ï„¡'
'code-oss' = 'ï„¡'
'Spotify' = 'ï†¼'
'/(?i)Github.*Firefox/' = 'ï„“'
'firefox' = 'ï‰©'
'Nightly' = 'ï‰©'
'firefoxdeveloperedition' = 'ï‰©'
'/nvim ?\w*/' = 'ï‰½'
'/\[?yazi\]? ?\w*/' = 'ï¼'
'/\[?ranger\]? ?\w*/' = 'ï¼'
'/npm/' = 'ï¹'
'/node/' = 'ï¹'
'/yarn/' = 'ï¹'
'Alacritty' = 'ï„ '
'Kitty' = 'ï„ '
'kitty' = 'ï„ '
'/WhatsApp/' = 'ïˆ²'
'/Binance/' = 'ï¹'
'/Trilium/' = 'ğŸ–º'
'/Obsidian/' = 'ğŸ–º'
