# hyprland-autoname-workspaces configuration
# Icons copied from sworkstyle config
# https://github.com/hyprland-community/hyprland-autoname-workspaces/blob/main/config.toml.example

version = "1.2.0"

[format]
dedup = true
dedup_inactive_fullscreen = false

[class]
DEFAULT = "ï‹"
"Alacritty" = "ï„ "
"Bitwarden" = "ï‚„"
"Brave" = "ï‰¨"
"Brave-browser" = "ï‰¨"
"Chromium" = "ï‰¨"
"Code" = "ï„¡"
"Google-chrome" = "ï‰¨"
"Kitty" = "ï„ "
"Nightly" = "ï‰©"
"Postman" = "ï "
"Slack" = "ï†˜"
"Steam" = "ï†¶"
"balena-etcher" = "ï‹›"
"brave-browser" = "ï‰¨"
"code-oss" = "ï„¡"
"discord" = "ï’"
"firefox" = "ï‰©"
"firefoxdeveloperedition" = "ï‰©"
"kitty" = "ï„ "
"spotify" = "ï†¼"
"steam" = "ï†¶"
"vlc" = "ï€½"

[title_in_class.".*"]
"(?i)Github.*Firefox" = "ï„“"
"Binance" = "ï¹"
"Chrome" = "ï‰¨"
"Obsidian" = "ğŸ–º"
"Trilium" = "ğŸ–º"
"WhatsApp" = "ïˆ²"
"\\[?ranger\\]? ?\\w*" = "ï¼"
"\\[?yazi\\]? ?\\w*" = "ï¼"
"node" = "ï¹"
"npm" = "ï¹"
"nvim ?\\w*" = "ï¯"
"yarn" = "ï¹"

[exclude]
"" = "^$"
